### PR TITLE
fix: make evaluate work with serializing Guids

### LINKED ISSUE #2374: [Bug] [Regression] [since 1.23] Parsing Guid values (IPage.EvaluateAsync<Guid>) using System.Convert class throws
This created very problematic regression for parsing Guid values.
`Convert.ChangeType("{08d15efd-bd4f-4244-b46e-2238964e0e36}", typeof(Guid), System.Globalization.CultureInfo.InvariantCulture)` throws

_Originally posted by @maw136 in https://github.com/microsoft/playwright-dotnet/issues/2178#issuecomment-1306371464_

### PR DESCRIPTION
**Pull request by feiyun0112**
Fixes #2374

### CODE REVIEW

File: src/Playwright/Helpers/Driver.cs [hunk 1]
```diff
@@ -34,7 +34,13 @@ internal static class Driver
 {
     internal static string GetExecutablePath()
     {
-        DirectoryInfo assemblyDirectory = new(AppContext.BaseDirectory);
+        string baseDirectory = Environment.GetEnvironmentVariable("PLAYWRIGHT_DRIVER_PATH");
```
Comment (pavelfeldman) [inline src/Playwright/Helpers/Driver.cs:37]: Looks like a stray change.

**Review by mxschmitt — APPROVED** [review]
