### PR TITLE
fix(websockets): filter for text and binary frames

### LINKED ISSUE #1624: [internal] Filter WebSocket frame events
Port https://github.com/microsoft/playwright-java/pull/522 for .NET

### PR DESCRIPTION
**Pull request by avodovnik**
Closes #1624

### CODE REVIEW

File: src/Playwright/Transport/Channels/WebSocketChannel.cs [hunk 1]
```diff
@@ -47,24 +47,41 @@ public WebSocketChannel(string guid, Connection connection, WebSocket owner) : b
 
         internal override void OnMessage(string method, JsonElement? serverParams)
         {
+            bool ShouldFilterOpCode(out int opcode)
```
Comment (mxschmitt) [inline src/Playwright/Transport/Channels/WebSocketChannel.cs:50]:
```suggestion
            bool IsTextOrBinaryFrame(out int opcode)
```

**Review by mxschmitt — APPROVED** [review]
ti: out-parameters
