### PR TITLE
fix: added support for HAR

### LINKED ISSUE #1841: [Bug]: HAR file not being saved
### Playwright version

1.17.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium, Firefox

### Other information

_No response_

### What happened? / Describe the bug

I am trying to record a HAR file with Playwright.

According to the docs, all you need to do is pass RecordHarPath in the BrowserContextOptions and call CloseAsync on the BrowserContext.

With Firefox, this is not creating any HAR file.
With Chromium, it hangs on CloseAsync and never completes.

### Code snippet to reproduce your bug

```shell
static async Task Main()
{
    var playwright = await Playwright.CreateAsync();

    var currentDir = Directory.GetCurrentDirectory();

    Console.WriteLine("Trying Firefox");
    var firefox = await playwright.Firefox.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false});
    await TryWith(firefox, Path.Combine(currentDir, "firefoxHar.har"));

    Console.WriteLine("Trying Chromium");
    var chromium = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false });
    await TryWith(chromium, Path.Combine(currentDir, "chromium.har"));
}

static async Task TryWith(IBrowser browser, string harPath)
{
    var context = await browser.NewContextAsync(new BrowserNewContextOptions()
    {
        RecordHarPath = harPath
    });

    var page = await context.NewPageAsync();
    await page.GotoAsync("https://www.microsoft.com");
    var link = await page.QuerySelectorAsync("a#uhf-shopping-cart");
    await link.ClickAsync();

    Console.WriteLine("Closing Context");
    await context.CloseAsync();
    Console.WriteLine("Closing Browser");
    await browser.CloseAsync();
}
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes #1841;

### CODE REVIEW

File: src/Playwright/Core/BrowserType.cs [hunk 1]
```diff
@@ -119,6 +119,16 @@ public async Task<IBrowserContext> LaunchPersistentContextAsync(string userDataD
                 ignoreAllDefaultArgs: options.IgnoreAllDefaultArgs,
                 baseUrl: options.BaseURL,
                 forcedColors: options.ForcedColors).ConfigureAwait(false)).Object;
+
+            // TODO: unite with a single browser context options type which is derived from channels
+            context.Options = new()
```
Comment (mxschmitt) [inline src/Playwright/Core/BrowserType.cs:124]: this needs a proper refactor, so we can share the same underlying types between NewContext and LaunchPersistentContext. For now just manually wrapping the values over.

File: src/Playwright/Core/Browser.cs [hunk 2]
```diff
@@ -105,7 +105,7 @@ public async Task<IBrowserContext> NewContextAsync(BrowserNewContextOptions opti
                strictSelectors: options.StrictSelectors,
                forcedColors: options.ForcedColors).ConfigureAwait(false)).Object;
 
-            context.RecordVideo = !string.IsNullOrEmpty(options.RecordVideoDir);
```
Comment (mxschmitt) [inline src/Playwright/Core/Browser.cs:108]: drive-by: moved over to the BrowserContext options

**Review by pavelfeldman — APPROVED** [review]
